### ISSUE TITLE
game installation/uninstallation is unreliable; causes crashes

### ISSUE THREAD

**Issue by TheSiege** [desura/desura-app#790]
while installing/uninstalling games (especially when there are leftover files) desurium crashes with the following error:

```
/var/tmp/portage/x11-libs/wxGTK-3.0.0.0/work/wxPython-src-3.0.0.0/src/gtk/bitmap.cpp(923): assert "IsOk()" failed in GetWidth(): invalid bitmap
/var/tmp/portage/x11-libs/wxGTK-3.0.0.0/work/wxPython-src-3.0.0.0/src/gtk/bitmap.cpp(916): assert "IsOk()" failed in GetHeight(): invalid bitmap

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff015e74e in wxWindowBase::FindFocus() () from /usr/lib64/libwx_gtk2u_core-3.0.so.0

```

following backtrace with gdb

```
#0  0x00007ffff015e74e in wxWindowBase::FindFocus() () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#1  0x00007ffff008f3d5 in wxControlContainerBase::DoSetFocus() () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#2  0x00007ffff3ceb8d0 in wxNavigationEnabled<wxWindow>::SetFocus() () from /home/anagromataf/github/desura-app/install/lib/libuicore.so
#3  0x00007fffefff628f in gtk_window_button_press_callback () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#4  0x00007ffff21d3715 in _gtk_marshal_BOOLEAN__BOXED () from /usr/lib64/libgtk-x11-2.0.so.0
#5  0x00007ffff1e01dd8 in g_closure_invoke () from /usr/lib64/libgobject-2.0.so.0
#6  0x00007ffff1e13833 in signal_emit_unlocked_R () from /usr/lib64/libgobject-2.0.so.0
#7  0x00007ffff1e1b3b9 in g_signal_emit_valist () from /usr/lib64/libgobject-2.0.so.0
#8  0x00007ffff1e1b9ba in g_signal_emit () from /usr/lib64/libgobject-2.0.so.0
#9  0x00007ffff22e2c54 in gtk_widget_event_internal () from /usr/lib64/libgtk-x11-2.0.so.0
#10 0x00007ffff21d1ec4 in gtk_propagate_event () from /usr/lib64/libgtk-x11-2.0.so.0
#11 0x00007ffff21d227b in gtk_main_do_event () from /usr/lib64/libgtk-x11-2.0.so.0
#12 0x00007fffb9d6ab14 in base::MessagePumpGtk::EventDispatcher(_GdkEvent*, void*) () from /home/anagromataf/github/desura-app/install/lib/libcef_desura.so
#13 0x00007ffff1865bcc in gdk_event_dispatch () from /usr/lib64/libgdk-x11-2.0.so.0
#14 0x00007ffff1b0ac56 in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
#15 0x00007ffff1b0afc8 in g_main_context_iterate.isra () from /usr/lib64/libglib-2.0.so.0
#16 0x00007ffff1b0b06c in g_main_context_iteration () from /usr/lib64/libglib-2.0.so.0
#17 0x00007ffff21d1561 in gtk_main_iteration () from /usr/lib64/libgtk-x11-2.0.so.0
#18 0x00007fffefff2765 in wxWindow::DoPopupMenu(wxMenu*, int, int) () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#19 0x00007ffff015deb3 in wxWindowBase::PopupMenu(wxMenu*, int, int) () from /usr/lib64/libwx_gtk2u_core-3.0.so.0
#20 0x00007ffff3d7b145 in ContextMenuExtender::showContextMenu(int, int, std::vector<std::map<gcBaseString<char>, gcBaseString<char>, std::less<gcBaseString<char> >, std::allocator<std::pair<gcBaseString<char> const, gcBaseString<char> > > >, std::allocator<std::map<gcBaseString<char>, gcBaseString<char>, std::less<gcBaseString<char> >, std::allocator<std::pair<gcBaseString<char> const, gcBaseString<char> > > > > >, ChromiumDLL::JSObjHandle, ChromiumDLL::JSObjHandle) () from /home/anagromataf/github/desura-app/install/lib/libuicore.so
#21 0x00007ffff3d7c7ac in JSDelegateVoidFunction<ContextMenuExtender, int, int, std::vector<std::map<gcBaseString<char>, gcBaseString<char>, std::less<gcBaseString<char> >, std::allocator<std::pair<gcBaseString<char> const, gcBaseString<char> > > >, std::allocator<std::map<gcBaseString<char>, gcBaseString<char>, std::less<gcBaseString<char> >, std::allocator<std::pair<gcBaseString<char> const, gcBaseString<char> > > > > >, ChromiumDLL::JSObjHandle, ChromiumDLL::JSObjHandle, PVoid>::operator()(ChromiumDLL::JavaScriptFactoryI*, ChromiumDLL::JavaScriptContextI*, ChromiumDLL::JSObjHandle, unsigned long, ChromiumDLL::JSObjHandle*) () from /home/anagromataf/github/desura-app/install/lib/libuicore.so
#22 0x00007ffff3e622eb in DesuraJSBaseNonTemplate::execute(ChromiumDLL::JavaScriptFunctionArgs*) () from /home/anagromataf/github/desura-app/install/lib/libuicore.so
#23 0x00007fffb9d62dba in JavaScriptExtender::Execute(CefStringBase<CefStringTraitsUTF8> const&, CefRefPtr<CefV8Value>, std::vector<CefRefPtr<CefV8Value>, std::allocator<CefRefPtr<CefV8Value> > > const&, CefRefPtr<CefV8Value>&, CefStringBase<CefStringTraitsUTF8>&) () from /home/anagromataf/github/desura-app/install/lib/libcef_desura.so
#24 0x00007fffba24192f in (anonymous namespace)::FunctionCallbackImpl(v8::Arguments const&) () from /home/anagromataf/github/desura-app/install/lib/libcef_desura.so
#25 0x00007fffba299a56 in v8::internal::Builtin_HandleApiCall(v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>, v8::internal::Isolate*) ()
   from /home/anagromataf/github/desura-app/install/lib/libcef_desura.so
#26 0x0000388a356d814e in ?? ()
#27 0x0000388a357a89f8 in ?? ()
#28 0x0000388a356d80c1 in ?? ()
#29 0x00007fffffffbe00 in ?? ()
#30 0x00007fffffffbe98 in ?? ()
#31 0x0000388a3596f463 in ?? ()
#32 0x00002f220ce09ee9 in ?? ()
#33 0x00002937c15efab1 in ?? ()
#34 0x00002937c15e7ad9 in ?? ()
#35 0x00002937c15e7b01 in ?? ()
#36 0x000001f000000000 in ?? ()
#37 0x000000e800000000 in ?? ()
#38 0x00002f220ce005e9 in ?? ()
#39 0x00002937c15e7b01 in ?? ()
#40 0x000001f000000000 in ?? ()
#41 0x000000e800000000 in ?? ()
#42 0x00002f220ce005e9 in ?? ()
#43 0x00002937c15e7b01 in ?? ()
#44 0x00000a19dd32c399 in ?? ()
#45 0x00000a19dd31a041 in ?? ()
#46 0x00007fffffffbf88 in ?? ()
#47 0x0000388a3594dcf2 in ?? ()
#48 0x00002937c15e0531 in ?? ()
#49 0x00002937c15e7ad9 in ?? ()
#50 0x0000000000000000 in ?? ()

```

**Comment by TheBeastie** [comment]
Even though this is Desurium, we fixed this in Desura-app:
https://github.com/desura/desura-app/commit/5b8bbba3e9c159844599a8992f802508b0327583
